
class LS_KEY {
	static ALLSHIP_TOGGLE_IS_CLOSE: string = "ALLSHIP_TOGGLE_IS_CLOSE";
	static MEMBER: string = "MEMBER";
	static ACTIVE_SHIP_ID = "ACTIVE_SHIP_ID";
	static ACTIVE_FLEET_ID = "ACTIVE_FLEET_ID";
	static FINAL_FLEET_SEQ = "FINAL_FLEET_SEQ";
	static FINAL_MEMBER_SEQ = "FINAL_MEMBER_SEQ";
}
