var LS_KEY = (function () {
    function LS_KEY() {
    }
    LS_KEY.ALLSHIP_TOGGLE_IS_CLOSE = "ALLSHIP_TOGGLE_IS_CLOSE";
    LS_KEY.MEMBER = "MEMBER";
    LS_KEY.ACTIVE_SHIP_ID = "ACTIVE_SHIP_ID";
    LS_KEY.ACTIVE_FLEET_ID = "ACTIVE_FLEET_ID";
    LS_KEY.FINAL_FLEET_SEQ = "FINAL_FLEET_SEQ";
    LS_KEY.FINAL_MEMBER_SEQ = "FINAL_MEMBER_SEQ";
    return LS_KEY;
})();
